#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/common/functions"

redirect_nginx_pre_load_trigger() {
  declare desc="add nginx redirect internal servers"

  local APP="$1"
  local APP_ROOT="$DOKKU_ROOT/$APP"
  local REDIRECT_FILE="$APP_ROOT/REDIRECTS_INTERNAL"
  local DIR="$DOKKU_ROOT/$APP/nginx.conf.d"

  [[ ! -s "$REDIRECT_FILE" ]] && trap "rm -f $DIR/redirect.conf" EXIT && exit 0

  if [ ! -d "$DIR/" ]; then
    mkdir "$DIR/"
  fi

  trap "mv $DIR/redirect.conf $DIR/redirect.conf.bak" EXIT

  local NGINX_CONF_PREPEND=$(mktemp)
  trap "rm -f \"$NGINX_CONF_PREPEND\"" EXIT

  touch "$NGINX_CONF_PREPEND"
  while read -r line; do
    [[ -z "$line" ]] && continue
    local DOMAIN=$(echo "$line" | awk -F ' ' '{ print $1 }')
    local DEST_DOMAIN=$(echo "$line" | awk -F ' ' '{ print $2 }')
    local REDIR_CODE=$(echo "$line" | awk -F ' ' '{ print $3 ? $3 : "301" }')
    dokku_log_info1 "Configuring redirect for $DOMAIN to $DEST_DOMAIN via HTTP $REDIR_CODE..."

    echo "location /$DOMAIN {
  return $REDIR_CODE \$scheme://\$host/$DEST_DOMAIN;
}" >>"$NGINX_CONF_PREPEND"
  done <<<"$(<"$REDIRECT_FILE")"

  if [[ -s "$NGINX_CONF_PREPEND" ]]; then
    cat "$NGINX_CONF_PREPEND" >"$DIR/redirect.conf"
  fi
}

redirect_nginx_pre_load_trigger "$@"
